/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Story = IDL.Record({
  'title' : IDL.Text,
  'authorName' : IDL.Opt(IDL.Text),
  'isAnonymous' : IDL.Bool,
  'story' : IDL.Text,
  'timestamp' : IDL.Int,
  'authorPseudonym' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SystemInfo = IDL.Record({ 'version' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminRewordAndPublishStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublishedStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getPublishedStory' : IDL.Func([IDL.Text], [Story], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requireAdmin' : IDL.Func([IDL.Principal], [], ['oneway']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'systemInfo' : IDL.Func([], [SystemInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Story = IDL.Record({
    'title' : IDL.Text,
    'authorName' : IDL.Opt(IDL.Text),
    'isAnonymous' : IDL.Bool,
    'story' : IDL.Text,
    'timestamp' : IDL.Int,
    'authorPseudonym' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SystemInfo = IDL.Record({ 'version' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminRewordAndPublishStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublishedStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getPublishedStory' : IDL.Func([IDL.Text], [Story], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requireAdmin' : IDL.Func([IDL.Principal], [], ['oneway']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'systemInfo' : IDL.Func([], [SystemInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };