/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Rating = IDL.Record({
  'reviewerHandle' : IDL.Text,
  'comment' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'rating' : IDL.Nat8,
});
export const ReviewThread = IDL.Record({
  'reviews' : IDL.Vec(Rating),
  'storyTitle' : IDL.Text,
});
export const Comment = IDL.Record({
  'comment' : IDL.Text,
  'timestamp' : Time,
  'commenterHandle' : IDL.Text,
});
export const CommentThread = IDL.Record({
  'storyTitle' : IDL.Text,
  'comments' : IDL.Vec(Comment),
});
export const Discussions = IDL.Record({
  'reviews' : IDL.Vec(ReviewThread),
  'comments' : IDL.Vec(CommentThread),
});
export const Story = IDL.Record({
  'title' : IDL.Text,
  'authorName' : IDL.Opt(IDL.Text),
  'isAnonymous' : IDL.Bool,
  'story' : IDL.Text,
  'timestamp' : Time,
  'authorPseudonym' : IDL.Text,
  'authorPrincipal' : IDL.Opt(IDL.Principal),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SubmissionStatus = IDL.Record({
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'published' : IDL.Null }),
  'story' : Story,
});
export const SystemInfo = IDL.Record({ 'version' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat8, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'adminRewordAndPublishStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkBackendHeartbeat' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllDiscussions' : IDL.Func([], [Discussions], ['query']),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(SubmissionStatus)], ['query']),
  'getPublishedStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getPublishedStory' : IDL.Func([IDL.Text], [Story], ['query']),
  'getStoryComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'systemInfo' : IDL.Func([], [SystemInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Rating = IDL.Record({
    'reviewerHandle' : IDL.Text,
    'comment' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'rating' : IDL.Nat8,
  });
  const ReviewThread = IDL.Record({
    'reviews' : IDL.Vec(Rating),
    'storyTitle' : IDL.Text,
  });
  const Comment = IDL.Record({
    'comment' : IDL.Text,
    'timestamp' : Time,
    'commenterHandle' : IDL.Text,
  });
  const CommentThread = IDL.Record({
    'storyTitle' : IDL.Text,
    'comments' : IDL.Vec(Comment),
  });
  const Discussions = IDL.Record({
    'reviews' : IDL.Vec(ReviewThread),
    'comments' : IDL.Vec(CommentThread),
  });
  const Story = IDL.Record({
    'title' : IDL.Text,
    'authorName' : IDL.Opt(IDL.Text),
    'isAnonymous' : IDL.Bool,
    'story' : IDL.Text,
    'timestamp' : Time,
    'authorPseudonym' : IDL.Text,
    'authorPrincipal' : IDL.Opt(IDL.Principal),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SubmissionStatus = IDL.Record({
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'published' : IDL.Null }),
    'story' : Story,
  });
  const SystemInfo = IDL.Record({ 'version' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat8, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'adminRewordAndPublishStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkBackendHeartbeat' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllDiscussions' : IDL.Func([], [Discussions], ['query']),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(SubmissionStatus)], ['query']),
    'getPublishedStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getPublishedStory' : IDL.Func([IDL.Text], [Story], ['query']),
    'getStoryComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'systemInfo' : IDL.Func([], [SystemInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };