/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'comment' : string,
  'timestamp' : Time,
  'commenterHandle' : string,
}
export interface CommentThread {
  'storyTitle' : string,
  'comments' : Array<Comment>,
}
export interface Discussions {
  'reviews' : Array<ReviewThread>,
  'comments' : Array<CommentThread>,
}
export interface Rating {
  'reviewerHandle' : string,
  'comment' : [] | [string],
  'timestamp' : Time,
  'rating' : number,
}
export interface ReviewThread {
  'reviews' : Array<Rating>,
  'storyTitle' : string,
}
export interface Story {
  'title' : string,
  'authorName' : [] | [string],
  'isAnonymous' : boolean,
  'story' : string,
  'timestamp' : Time,
  'authorPseudonym' : string,
  'authorPrincipal' : [] | [Principal],
}
export interface SubmissionStatus {
  'status' : { 'pending' : null } |
    { 'published' : null },
  'story' : Story,
}
export interface SystemInfo { 'version' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string, string], undefined>,
  'addReview' : ActorMethod<[string, string, number, [] | [string]], undefined>,
  'adminCreateAndPublishArticle' : ActorMethod<
    [string, string, string, boolean, [] | [string], [] | [Principal]],
    undefined
  >,
  'adminRewordAndPublishStory' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkBackendHeartbeat' : ActorMethod<[], boolean>,
  'getAllDiscussions' : ActorMethod<[], Discussions>,
  'getAllStories' : ActorMethod<[], Array<Story>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMySubmissions' : ActorMethod<[], Array<SubmissionStatus>>,
  'getPublishedStories' : ActorMethod<[], Array<Story>>,
  'getPublishedStory' : ActorMethod<[string], Story>,
  'getStoryComments' : ActorMethod<[string], Array<Comment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitStory' : ActorMethod<
    [string, string, string, boolean, [] | [string]],
    undefined
  >,
  'systemInfo' : ActorMethod<[], SystemInfo>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];